name: Deploy backend to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH & Restart Docker container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/BE-basic-Sgroup
            git pull origin main

            echo "Stopping old container..."
            docker stop backend-container || true
            docker rm backend-container || true

            echo "Building new image..."
            docker build -t my-backend-app .

            echo "Running new container..."
            docker run -d -p 8000:8000 --name backend-container my-backend-app
